### ISSUE TITLE
Playback Resumer not working with Kodi Nexus

### ISSUE THREAD

**Issue by yanivlavi** [bossanova808/script.service.playbackresumer#7] opened 2023-04-25 07:26 UTC
The addon stopped working with Kodi nexus. It's this a known issue?

**Comment by yanivlavi** [comment] 2023-04-27 09:54
I'm using latest Kodi for Xbox. 
The main function is not working at all for me. Meaning if Kodi crashes during playback it doesn't remember the last resume position. The movie/show does show up in 'continue playing' but it starts from the beginning.

**Comment by bossanova808** [comment] 2023-04-27 09:59
Can you post a debug log of this somewhere?  Or even start with a debug log of normal playback.

I don't know if there is anything different about the xbox Kodi, but you should see it setting the resume points, and then it asks Kodi to report the resume point, which should match what it was set to (over and over again obviously).

**Comment by yanivlavi** [comment] 2023-04-30 07:59
Give me a few days to do that.

**Comment by yanivlavi** [comment] 2023-05-08 06:56
I turned on debug and I saw the script running, but I still get resume point not being saved.
Any advice on what to check next?

**Comment by bossanova808** [comment] 2023-05-08 07:13
Can you show me the log?  might give me some clues.  But otherwise - no real idea really, sorry, it seems to be working ok here and setting (and confirming) the resume points along the way...

I wonder if something else is then wiping the resume point (Trakt sync or whatever)....

**Comment by yanivlavi** [comment] 2023-07-06 20:28
I was about to reproduce, but I still need to figure out how to get the logs. The issue happens when you pause a video and then leave it like that for a long time until the device shuts down.
In my case, I watch something, pause, long time passes and the xBox shuts off. When I reopen Kodi the position is lost.

**Comment by bossanova808** [comment] 2023-07-07 00:11
Am going to close this again - without a log of a problem I can't reproduce, there isn't much I can do.  When/if you do produce a log, please re-open it then.  It's highly likely it's a Kodi problem rather than a problem with this addon (although not certain of course) - the log will show what the addon is doing.  I'm sure Google will have some info about getting to the logs on the xBox, but I've never used one, so no idea on that, sorry.

**Closed by bossanova808** 2023-07-07 00:11 UTC
